In [6]:
import torch

Creating Tensors

In [7]:
# Creating 1-D tensor
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print(f"1-D tensor: {tensor_1d}")
print("-"*30)

# Creating 2-D tensor
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"2-D tensor: \n{tensor_2d}")
print("-"*30)

# Creating a tensor of 0 values
tensor_0 = torch.zeros(3, 4)
print(f"Tensor with 0 values: \n{tensor_0}")
print("-"*30)

# Creating a tensor of ones
tensor_1 = torch.ones(3, 4)
print(f"Tensor with 1 values: \n{tensor_1}")

1-D tensor: tensor([1, 2, 3, 4, 5])
------------------------------
2-D tensor: 
tensor([[1, 2, 3],
        [4, 5, 6]])
------------------------------
Tensor with 0 values: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
------------------------------
Tensor with 1 values: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


Simple Operations on Tensors

In [8]:
tensor_a = torch.tensor([[1, 2], [3, 4]])
tensor_b = torch.tensor([[5, 6], [7, 8]])

# Element wise addition
tensor_sum = tensor_a + tensor_b
print(f"After addition: \n{tensor_sum}")
print("-"*30)

# Element wise multiplication
tensor_mul = tensor_a * tensor_b
print(f"After addition: \n{tensor_mul}")
print("-"*30)

# Matrix multiplication
tensor_matmul = torch.matmul(tensor_a, tensor_b)
print(f"After addition: \n{tensor_matmul}")
print("-"*30)

# Reshaping Tensors
tensor_orig = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"Original reshaping the tensor: \n{tensor_orig}")
reshaped_tensor = tensor_orig.view(3, 2) # Reshaping into 3X2
print(f"After reshaping the tensor: \n{reshaped_tensor}")

After addition: 
tensor([[ 6,  8],
        [10, 12]])
------------------------------
After addition: 
tensor([[ 5, 12],
        [21, 32]])
------------------------------
After addition: 
tensor([[19, 22],
        [43, 50]])
------------------------------
Original reshaping the tensor: 
tensor([[1, 2, 3],
        [4, 5, 6]])
After reshaping the tensor: 
tensor([[1, 2],
        [3, 4],
        [5, 6]])


Indexing and Slicing

In [11]:
tensor = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Original Tensor: \n{tensor}")
print(tensor[0, 1])
print("-"*30)

# Access an element
print(tensor[0, 1])
print("-"*30)

# Slice row and columns
print(tensor[:, 1])
print("-"*30)

# Boolean Indexing
mask = tensor > 7
print(tensor[mask])

Original Tensor: 
tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
tensor(2)
------------------------------
tensor(2)
------------------------------
tensor([2, 5, 8])
------------------------------
tensor([8, 9])
