In [1]:
import torch

Creating Tensors

In [4]:
# Creating 1-D tensor
tensor_1d = torch.tensor([1, 2, 3, 4, 5])
print(f"1-D tensor: {tensor_1d}")
print("-"*30)

# Creating 2-D tensor
tensor_2d = torch.tensor([[1, 2, 3], [4, 5, 6]])
print(f"2-D tensor: \n{tensor_2d}")
print("-"*30)

# Creating a tensor of 0 values
tensor_0 = torch.zeros(3, 4)
print(f"Tensor with 0 values: \n{tensor_0}")
print("-"*30)

# Creating a tensor of ones
tensor_1 = torch.ones(3, 4)
print(f"Tensor with 1 values: \n{tensor_1}")

1-D tensor: tensor([1, 2, 3, 4, 5])
------------------------------
2-D tensor: 
tensor([[1, 2, 3],
        [4, 5, 6]])
------------------------------
Tensor with 0 values: 
tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
------------------------------
Tensor with 1 values: 
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
