In [1]:
import torch
import numpy as np

##### Training Data

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype = "float32")

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype = "float32")

In [4]:
# converting into pytorch tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


##### Linear Regression Model from scratch

In [5]:
# Weights and Biases
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

print(w)
print(b)

tensor([[-0.1053,  0.5256,  0.4696],
        [ 1.2198, -0.5685, -2.2381]], requires_grad=True)
tensor([-0.5579, -1.0130], requires_grad=True)


In [6]:
def model(x):
    return x @ w.t() + b

In [7]:
# generate Predictions
preds = model(inputs)
print(preds)

tensor([[  47.1615,  -46.2935],
        [  66.1647,  -83.2751],
        [  87.9478, -100.8753],
        [  28.6743,   16.1527],
        [  75.5045, -128.0872]], grad_fn=<AddBackward0>)


In [8]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


##### Loss Function

In [9]:
# MSE Loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

`torch.sum` returns the sum of the tensors and `.numel` returns the number of elements.

In [10]:
# Compute loss
loss = mse(t1 = preds, t2 = targets)
print(loss)

tensor(16572.8828, grad_fn=<DivBackward0>)


##### Compute Gradients 

In [11]:
loss.backward()

In [12]:
print(w)
print(w.grad)

tensor([[-0.1053,  0.5256,  0.4696],
        [ 1.2198, -0.5685, -2.2381]], requires_grad=True)
tensor([[ -1182.6355,  -1682.2511,   -961.6560],
        [-12956.2109, -15992.7939,  -9685.2891]])


In [13]:
print(b)
print(b.grad)

tensor([-0.5579, -1.0130], requires_grad=True)
tensor([ -15.1094, -160.4757])


In [14]:
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

In [16]:
preds = model(inputs)
print(preds)

tensor([[ 49.5656, -21.9540],
        [ 69.3369, -51.2111],
        [ 91.7888, -62.5540],
        [ 30.9599,  39.8301],
        [ 78.6088, -97.0130]], grad_fn=<AddBackward0>)


In [17]:
loss = mse(t1 = preds, t2 = targets)
print(loss)

tensor(11812.7832, grad_fn=<DivBackward0>)


In [18]:
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


##### Training for epochs

In [36]:
# train for 1000 epochs
for i in range(1000):
    preds = model(inputs)
    loss = mse(preds, targets)
    loss.backward()
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [37]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.4938, grad_fn=<DivBackward0>)


In [38]:
# Predictions
preds

tensor([[ 57.0708,  70.1396],
        [ 82.2660, 100.7764],
        [118.7085, 132.9861],
        [ 21.0932,  37.0365],
        [101.9054, 119.1107]], grad_fn=<AddBackward0>)

In [39]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

### Linear Regression using PyTorch built-ins