In [ ]:
# Importing torch and numpy
import torch
import numpy as np

##### Training Data

Creating synthetic dataset for the model to train on

In [ ]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70]], dtype = "float32")

In [3]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119]], dtype = "float32")

In [4]:
# converting into pytorch tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


##### Linear Regression Model from scratch

In [ ]:
# Initialising the Weights and Biases
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)

print(w)
print(b)

tensor([[-0.1053,  0.5256,  0.4696],
        [ 1.2198, -0.5685, -2.2381]], requires_grad=True)
tensor([-0.5579, -1.0130], requires_grad=True)


In [ ]:
# Defining a Simple Linear Regression model
def model(x):

    """
    x @ w: It is used for matrix multiplication
    w.t(): It is used to get the transpose of the matrix
    """
    return x @ w.t() + b

In [7]:
# generate Predictions
preds = model(inputs)
print(preds)

tensor([[  47.1615,  -46.2935],
        [  66.1647,  -83.2751],
        [  87.9478, -100.8753],
        [  28.6743,   16.1527],
        [  75.5045, -128.0872]], grad_fn=<AddBackward0>)


In [8]:
print(targets)

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


##### Loss Function

In [ ]:
# MSE (Mean Squarred Error)Loss
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

`torch.sum` returns the sum of the tensors and `.numel` returns the number of elements.

In [10]:
# Compute loss
loss = mse(t1 = preds, t2 = targets)
print(loss)

tensor(16572.8828, grad_fn=<DivBackward0>)


##### Compute Gradients 

In [ ]:
# Backpropagation
loss.backward()

In [12]:
print(w)
print(w.grad)

tensor([[-0.1053,  0.5256,  0.4696],
        [ 1.2198, -0.5685, -2.2381]], requires_grad=True)
tensor([[ -1182.6355,  -1682.2511,   -961.6560],
        [-12956.2109, -15992.7939,  -9685.2891]])


In [13]:
print(b)
print(b.grad)

tensor([-0.5579, -1.0130], requires_grad=True)
tensor([ -15.1094, -160.4757])


In [ ]:
# Changing the weights and biases
with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5

By using `torch.no_grad()`, we can let the torch knows that we do not want to record this calculation for the backpropagation.

In [16]:
preds = model(inputs)
print(preds)

tensor([[ 49.5656, -21.9540],
        [ 69.3369, -51.2111],
        [ 91.7888, -62.5540],
        [ 30.9599,  39.8301],
        [ 78.6088, -97.0130]], grad_fn=<AddBackward0>)


In [17]:
loss = mse(t1 = preds, t2 = targets)
print(loss)

tensor(11812.7832, grad_fn=<DivBackward0>)


In [ ]:
# Changing the gardients to 0
w.grad.zero_()
b.grad.zero_()

print(w.grad)
print(b.grad)

tensor([[0., 0., 0.],
        [0., 0., 0.]])
tensor([0., 0.])


##### Training for epochs

In [ ]:
# train for 1000 epochs
for i in range(1000):

    # Generating the preedictions
    preds = model(inputs)

    # Calculating the loss
    loss = mse(preds, targets)

    # Backpropagation
    loss.backward()

    # Parameters updates
    with torch.no_grad():
        w -= w.grad * 1e-5
        b -= b.grad * 1e-5
        w.grad.zero_()
        b.grad.zero_()

In [37]:
# Calculate loss
preds = model(inputs)
loss = mse(preds, targets)
print(loss)

tensor(0.4938, grad_fn=<DivBackward0>)


In [38]:
# Predictions
preds

tensor([[ 57.0708,  70.1396],
        [ 82.2660, 100.7764],
        [118.7085, 132.9861],
        [ 21.0932,  37.0365],
        [101.9054, 119.1107]], grad_fn=<AddBackward0>)

In [39]:
targets

tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])

### Linear Regression using PyTorch built-ins

In [40]:
import torch.nn as nn

In [41]:
# Input (temp, rainfall, humidity)
inputs = np.array([[73, 67, 43],
                   [91, 88, 64],
                   [87, 134, 58],
                   [102, 43, 37],
                   [69, 96, 70],
                   [74, 66, 43],
                   [91, 87, 65],
                   [88, 134, 59],
                   [101, 44, 37],
                   [68, 96, 71],
                   [73, 66, 44],
                   [92, 87, 64],
                   [87, 135, 57],
                   [103, 43, 36],
                   [68, 97, 70]], dtype='float32')

In [ ]:
# Targets (apples, oranges)
targets = np.array([[56, 70],
                    [81, 101],
                    [119, 133],
                    [22, 37],
                    [103, 119],
                    [57, 69],
                    [80, 102],
                    [118, 132],
                    [21, 38],
                    [104, 118],
                    [57, 69],
                    [82, 100],
                    [118, 134],
                    [20, 38],
                    [102, 120]], dtype='float32')

# converting into PyTorch tensors
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [43]:
print(inputs)
print(targets)

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.],
        [ 74.,  66.,  43.],
        [ 91.,  87.,  65.],
        [ 88., 134.,  59.],
        [101.,  44.,  37.],
        [ 68.,  96.,  71.],
        [ 73.,  66.,  44.],
        [ 92.,  87.,  64.],
        [ 87., 135.,  57.],
        [103.,  43.,  36.],
        [ 68.,  97.,  70.]])
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 57.,  69.],
        [ 80., 102.],
        [118., 132.],
        [ 21.,  38.],
        [104., 118.],
        [ 57.,  69.],
        [ 82., 100.],
        [118., 134.],
        [ 20.,  38.],
        [102., 120.]])


##### Dataset and Dataloader

In [44]:
from torch.utils.data import TensorDataset

In [46]:
# Define Dataset
train_ds = TensorDataset(inputs, targets)
train_ds[:3]

(tensor([[ 73.,  67.,  43.],
         [ 91.,  88.,  64.],
         [ 87., 134.,  58.]]),
 tensor([[ 56.,  70.],
         [ 81., 101.],
         [119., 133.]]))

In [47]:
from torch.utils.data import DataLoader

In [49]:
# Define Data Loader
batch_size = 5
train_dl = DataLoader(train_ds, batch_size = batch_size, shuffle = True)

In [50]:
for xb, yb in train_dl:
    print(xb)
    print(yb)
    break

tensor([[ 87., 135.,  57.],
        [ 88., 134.,  59.],
        [ 74.,  66.,  43.],
        [101.,  44.,  37.],
        [103.,  43.,  36.]])
tensor([[118., 134.],
        [118., 132.],
        [ 57.,  69.],
        [ 21.,  38.],
        [ 20.,  38.]])


##### nn.Linear

In [51]:
model = nn.Linear(3, 2)
print(model.weight)
print(model.bias)

Parameter containing:
tensor([[ 0.0699,  0.2609,  0.4203],
        [-0.3459,  0.3926, -0.5025]], requires_grad=True)
Parameter containing:
tensor([-0.2487, -0.3908], requires_grad=True)


In [52]:
# Parameters
list(model.parameters())

[Parameter containing:
 tensor([[ 0.0699,  0.2609,  0.4203],
         [-0.3459,  0.3926, -0.5025]], requires_grad=True),
 Parameter containing:
 tensor([-0.2487, -0.3908], requires_grad=True)]

In [53]:
preds = model(inputs)
preds

tensor([[ 40.4083, -20.9456],
        [ 55.9720, -29.4805],
        [ 65.1707,  -7.0240],
        [ 33.6534, -37.3815],
        [ 59.0424, -21.7465],
        [ 40.2174, -21.6840],
        [ 56.1314, -30.3756],
        [ 65.6609,  -7.8724],
        [ 33.8444, -36.6431],
        [ 59.3928, -21.9032],
        [ 40.5677, -21.8407],
        [ 55.7811, -30.2189],
        [ 65.0113,  -6.1289],
        [ 33.3031, -37.2248],
        [ 59.2333, -21.0081]], grad_fn=<AddmmBackward0>)

##### Loss Function

In [54]:
# Importing the nn.Functional
import torch.nn.functional as F

In [55]:
# Define loss
loss_fn = F.mse_loss

In [56]:
loss = loss_fn(model(inputs), targets)
print(loss)

tensor(7614.6592, grad_fn=<MseLossBackward0>)


##### Optimizer

In [57]:
opt = torch.optim.SGD(model.parameters(), lr = 1e-5)

##### Train the model

In [58]:
def fit(num_epochs, model, loss_fn, opt, train_dl):

    # Repeat the training for number of epochs
    for epoch in range(num_epochs):

        # Traing with batches of data
        for xb, yb in train_dl:

            # 1. Generate predctions
            pred = model(xb)

            # 2. Compute loss
            loss = loss_fn(pred, yb)

            # 3. Compute gradients
            loss.backward()

            # 4. Update parameters using gradients
            opt.step()

            # 5. Clear the gradients
            opt.zero_grad()

        # Print progress
        if (epoch + 1) % 10 == 0:
            print("Epoch [{}/{}], Loss: {}".format(epoch+1, num_epochs, loss.item()))

In [59]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 349.5077209472656
Epoch [20/100], Loss: 242.70999145507812
Epoch [30/100], Loss: 106.47581481933594
Epoch [40/100], Loss: 102.33531188964844
Epoch [50/100], Loss: 94.5625991821289
Epoch [60/100], Loss: 63.911346435546875
Epoch [70/100], Loss: 49.328575134277344
Epoch [80/100], Loss: 72.1596450805664
Epoch [90/100], Loss: 30.041675567626953
Epoch [100/100], Loss: 33.79077911376953
