Let's first import the `torch` library.

In [1]:
import torch

##### Tensors

In PyTorch, tensors are multidimensional arrays that serve as the basic data structure for computations, similar to NumPy arrays but optimized for GPU acceleration. They support automatic differentiation, enabling efficient gradient computations for deep learning tasks.

In [2]:
# Number
t1 = torch.tensor(4.)
t1

tensor(4.)

In [3]:
t1.dtype

torch.float32

In [4]:
# Vector
t2 = torch.tensor([1., 2., 3., 4., 5.])
t2

tensor([1., 2., 3., 4., 5.])

In [5]:
t2.dtype

torch.float32

In [6]:
# Matrix

t3 = torch.tensor([[1., 2., 3.],
                  [4., 5., 6.],
                  [7., 8., 9.]])
t3

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

To check the dimensionality of the tensors, we can use the `shape` function.

In [7]:
t3.shape

torch.Size([3, 3])

We can't make a matrix with different dimensions in each row

In [8]:
t4 = torch.tensor([[1., 2., 3.],
                   [4., 5.]])

t4

ValueError: expected sequence of length 3 at dim 1 (got 2)

##### Tensor Operations

`torch.tensor()` creates tensors, and setting `requires_grad = True` enables tracking of gradients for these tensors during computation.

In [11]:
# Creating Tensors

x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)

When performing operations (e.g., `y = w * x + b`), PyTorch creates a computational graph to track operations for automatic differentiation.

In [12]:
# Applying Arithmetic Operations on it
y = w * x + b
y

tensor(17., grad_fn=<AddBackward0>)

Calling `y.backward()` computes the gradients of `y` with respect to the tensors marked with `requires_grad = True`.

In [13]:
y.backward()

Gradients can be accessed using `.grad`. For example, `dy/dw` equals `x` and `dy/db` equals `1`, while `dy/dx` is `None` since `x` does not require a gradient.

In [14]:
# Displaying Gradients
print("dy/dx: ", x.grad)
print("dy/dw: ", w.grad)
print("dy/db: ", b.grad)

dy/dx:  None
dy/dw:  tensor(3.)
dy/db:  tensor(1.)


##### Tensor Functions

In [18]:
t6 = torch.full((2, 3), 42)
t6

tensor([[42, 42, 42],
        [42, 42, 42]])

In [19]:
t7 = torch.cat((t3, t6))
t7

tensor([[ 1.,  2.,  3.],
        [ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [42., 42., 42.],
        [42., 42., 42.]])

In [21]:
t8 = torch.sin(t7)
t8

tensor([[ 0.8415,  0.9093,  0.1411],
        [-0.7568, -0.9589, -0.2794],
        [ 0.6570,  0.9894,  0.4121],
        [-0.9165, -0.9165, -0.9165],
        [-0.9165, -0.9165, -0.9165]])

In [23]:
t9 = t8.reshape(3, 5)
t9

tensor([[ 0.8415,  0.9093,  0.1411, -0.7568, -0.9589],
        [-0.2794,  0.6570,  0.9894,  0.4121, -0.9165],
        [-0.9165, -0.9165, -0.9165, -0.9165, -0.9165]])

##### Interoperability with NumPy

In [24]:
import numpy as np

In [25]:
x = np.array([[1, 2],
              [3, 4.]])

x

array([[1., 2.],
       [3., 4.]])

In [26]:
y = torch.from_numpy(x)
y

tensor([[1., 2.],
        [3., 4.]], dtype=torch.float64)

In [27]:
x.dtype, y.dtype

(dtype('float64'), torch.float64)

In [28]:
z = y.numpy()
z

array([[1., 2.],
       [3., 4.]])